### ISSUE TITLE
Search interface and parent/child handling

### ISSUE THREAD

**Issue by steingod** [metno/metsis-drupal#20]
Ideally users should only see parent (or level 1) records. When the search the level2 (child) records for a parent/child dataset that fulfill the criteria (e.g. in time or space) should be exposed as they dig into the chdilren of a dataset. 

As it is today we have for many portals a hardcoded link to parent datasets in the menu, but this is broken once the user resets the user interface and then we confuse the users. How can we handle this in a more user friendly manner?

**Comment by magnarem** [comment]
Ideally we implement this as a filter in the metsis search view with possible exposed form, instead of hardcoded urls for the dataset type facet filter.

**Comment by magnarem** [comment]
This is now fixed in the latest metsis-drupal.

data-dev.met.no, data-staging.met.no and data.met.no. Now use the new interface.

also metsis-staging.met.no. Use the new interface.

This can be closed now.

**Comment by magnarem** [comment]
closing this issue
