### ISSUE TITLE
Simplified search interface

### ISSUE THREAD

**Issue by steingod** [metno/metsis-drupal#21]
There is a user request for a simpler search interface for less advanced users. Typically this could be a free text search combined with a date and space constraint. 

In the current setup it is not possible to reuse elements in a more open setup of the user interface as once blocks are located in a container they are supposed to be there on other pages as well. Do we have a mechanism to circumvent this? Alternatively a receipt that is not too complicated to generate a simple search interface from scratch?

The challenge is that users often provide conflicting information so the ability to quickly change the view is good for user uptake.

**Comment by magnarem** [comment]
I will start to implement a new version of this in metsis-staging and try as a seperate view.

**Comment by steingod** [comment]
Looks good. Concerning date I think a dataset coverage with dates would be needed, this would be a bit too sparse for most use cases (although good for NBS with satellite selectors instead). How much work would the more than this functionality require?

**Comment by magnarem** [comment]
Added Download button and dateRange search to simple search. Latest can be tested on metsis-staging.met.no.

Next will be to implement parent/child relation support for the simple search.

**Comment by magnarem** [comment]
Added visualise button and some parent child handeling/grouping of results.
The lastes version of simple_search are now deployed to the staging servers (metsis-staging.met.no and nbs-staging.met.no

**Comment by magnarem** [comment]
We need to figure out how to handle parent/child in the search, so it will be intuitive for the user.


There are posibilities do do subquiries in solr to gather children for parent in the result list.
http://157.249.74.44:8983/solr/#/testcore/query?q=full_text:(%2Bweather%20%2Bstation)&q.op=OR&indent=true&fl=id,title,children:%5Bsubquery%5D,is*,related_dataset_id&sort=timestamp%20desc&children.q=full_text:(%2Bweather%20%2Bstation)%20AND%20%7B!terms%20f%3Drelated_dataset_id%20v%3D$row.id%7D&children.rows=5&children.fl=id,title,is*,related_dataset_id&fq=isParent:true%20or%20isParent:false&fq=isChild:false

http://157.249.74.44:8983/solr/#/testcore/query?q=full_text:(%2Bosisaf)&q.op=OR&indent=true&fl=id,title,children:%5Bsubquery%5D,is*,related_dataset_id&sort=timestamp%20desc&children.q=f%7B!terms%20f%3Drelated_dataset_id%20v%3D$row.id%7D&children.rows=5&children.fl=id,title,is*,related_dataset_id&fq=isParent:true%20or%20isParent:false&fq=isChild:false

But how drupal/search_api(solr) views handeling this. I will have to investigate.
Also parents with children who have the searched keywords in the children record but not in the parent record, will not show. Well need to check if there are workarounds for this.

**Comment by magnarem** [comment]
Closing this. New issues can be created regarding the simple search. Also create a card in NC to keep track of issues related to the simple_search.
