### ISSUE TITLE
The parent dataset link and information on the dataset landing page is a bit unclear

### ISSUE THREAD

**Issue by mortenwh** [metno/metsis-drupal#26]
I propose to change from 

> This is a child dataset. See the parent [Landing Page](https://data-test.met.no/dataset/f6cbb81c-1ce1-4080-b242-819e59cee78d) for more information.

To

> Parent dataset: https://data-test.met.no/dataset/f6cbb81c-1ce1-4080-b242-819e59cee78d

Or, also

> This is a child dataset. See the [Parent Dataset Landing Page](https://data-test.met.no/dataset/f6cbb81c-1ce1-4080-b242-819e59cee78d) for more information.

**Comment by magnarem** [comment]
Changed to : This is a child dataset. See the [Parent Dataset Landing Page](https://data-test.met.no/dataset/f6cbb81c-1ce1-4080-b242-819e59cee78d) for more information.

Closing this issue
