### ISSUE TITLE
Add mmd export to landing pages

### ISSUE THREAD

**Issue by magnarem** [metno/metsis-drupal#28]
In the landingpages users can export to dif, iso and inspire. But we are missing export to mmd.

Implement this.

**Comment by magnarem** [comment]
Do we really need it as MMD is more an internal format and not used by others?
Still the user can export as MMD in the search results interface.
@ferrighi @mortenwh @steingod

**Comment by steingod** [comment]
It is probably more for our own usage, export to standardised formats is more important I would say, but will also be lossy. If it is available in search results, can't it be reused? So for me it is not a requirement, more nice to have and depends cost of implementation.

**Comment by magnarem** [comment]
This is now implemented. One line of code extra to add this functionality. Closing
