### ISSUE TITLE
Fix web page cashing on search interface

### ISSUE THREAD

**Issue by hevgyrt** [metno/metsis-drupal#33]
There is some cashing in the search interface module, such that a cashed page is shown when it is visited. As a consequence, the latest satellite products are not shown in satellittdata.no. More recent products should be shown. If possible, I suggest to revoke the cashing on an hourly, or even shorter, basis

**Comment by magnarem** [comment]
Still I do not get the latest products. I will investigate more.

**Comment by magnarem** [comment]
Looks like it works now. Will verify during this week.

**Comment by magnarem** [comment]
Disabling solr document result cache fixes the problem. Will update all sites with new config

**Comment by magnarem** [comment]
All sites updated. @hevgyrt . Can you confirm that satellittdata.no show the latest products in the search interface using anonymous user i.e. private window or something. If everything looks good we can close this

**Comment by hevgyrt** [comment]
Thanks @magnarem. From testing on both chrome and firefox, this looks good to me. Thus closing task.
